import { NextResponse } from "next/server"
import { renderToBuffer } from "@react-pdf/renderer"
import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer"
import { auth } from "@/auth"
import { prisma } from "@/lib/prisma"

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 10, fontFamily: "Helvetica" },
  header: { marginBottom: 24, borderBottom: 2, borderBottomColor: "#0B1F3A", paddingBottom: 14 },
  brand: { fontSize: 16, fontWeight: 700, color: "#0B1F3A" },
  status: { fontSize: 9, color: "#3F6B4E", marginTop: 6, fontWeight: 700 },
  amountBox: { alignItems: "center", marginVertical: 24 },
  amountLabel: { fontSize: 9, color: "#5B6478", marginBottom: 4 },
  amount: { fontSize: 28, fontWeight: 700, color: "#0B1F3A" },
  row: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 8, borderBottom: 1, borderBottomColor: "#DCD4BF" },
  label: { color: "#5B6478" },
  value: { fontWeight: 700 },
  footer: { marginTop: 30, fontSize: 8, color: "#5B6478", textAlign: "center" },
})

function ReceiptDoc({
  type,
  status,
  amount,
  description,
  category,
  fromLabel,
  toLabel,
  date,
  reference,
}: {
  type: string
  status: string
  amount: number
  description: string
  category: string
  fromLabel: string
  toLabel: string
  date: string
  reference: string
}) {
  const fmt = `$${amount.toLocaleString("en-US", { minimumFractionDigits: 2 })}`
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.brand}>Anchor</Text>
          <Text style={{ fontSize: 9, color: "#5B6478", marginTop: 4 }}>Transaction Receipt</Text>
          <Text style={styles.status}>{status}</Text>
        </View>

        <View style={styles.amountBox}>
          <Text style={styles.amountLabel}>{description}</Text>
          <Text style={styles.amount}>{fmt}</Text>
        </View>

        <View style={styles.row}>
          <Text style={styles.label}>Type</Text>
          <Text style={styles.value}>{type}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Category</Text>
          <Text style={styles.value}>{category}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>From</Text>
          <Text style={styles.value}>{fromLabel}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>To</Text>
          <Text style={styles.value}>{toLabel}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Date</Text>
          <Text style={styles.value}>{date}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Reference ID</Text>
          <Text style={styles.value}>{reference}</Text>
        </View>

        <Text style={styles.footer}>
          This receipt was generated by Anchor and reflects the transaction record on file at time of generation.
        </Text>
      </Page>
    </Document>
  )
}

export async function GET(req: Request, { params }: { params: Promise<{ id: string }> }) {
  const session = await auth()
  if (!session?.user?.id) {
    return NextResponse.json({ error: "Not authenticated" }, { status: 401 })
  }

  const { id } = await params
  const tx = await prisma.transaction.findUnique({
    where: { id },
    include: {
      sourceAccount: { select: { userId: true, nickname: true, type: true } },
      destinationAccount: { select: { userId: true, nickname: true, type: true } },
    },
  })

  if (!tx) {
    return NextResponse.json({ error: "Transaction not found" }, { status: 404 })
  }

  const userId = session.user.id
  const ownsSource = tx.sourceAccount?.userId === userId
  const ownsDest = tx.destinationAccount?.userId === userId
  if (!ownsSource && !ownsDest) {
    return NextResponse.json({ error: "Transaction not found" }, { status: 404 })
  }

  const label = (acc: typeof tx.sourceAccount) =>
    acc ? acc.nickname || (acc.type === "CHECKING" ? "Checking" : "Savings") : "External"

  const typeLabels: Record<string, string> = {
    TRANSFER_INTERNAL: "Internal Transfer",
    TRANSFER_P2P: "Transfer",
    TRANSFER_EXTERNAL: "External Transfer",
    DEPOSIT: "Deposit",
    WITHDRAWAL: "Withdrawal",
    BILL_PAYMENT: "Bill Payment",
    FEE: "Fee",
  }

  const pdfBuffer = await renderToBuffer(
    <ReceiptDoc
      type={typeLabels[tx.type] ?? tx.type}
      status={tx.status}
      amount={Number(tx.amount)}
      description={tx.description ?? tx.category ?? tx.type}
      category={tx.category ?? "—"}
      fromLabel={label(tx.sourceAccount)}
      toLabel={tx.counterpartyName ?? label(tx.destinationAccount)}
      date={tx.createdAt.toLocaleString("en-US", { dateStyle: "long", timeStyle: "short" })}
      reference={tx.id}
    />
  )

  return new NextResponse(new Uint8Array(pdfBuffer), {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="receipt-${tx.id.slice(-8)}.pdf"`,
    },
  })
}
